# Site settings
title: jawadefaj
# general_email: unique.corn.uc@gmail.com
academic_email: abjawad@ucsc.edu

description: > # this means to ignore newlines until "baseurl:"
  copyright &copy; 2023 jawadefaj. All rights reserved.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://jawadefaj.xyz/" # the base hostname & protocol for your site

github_username: jawadefaj
linkedin_username: jawadefaj
# researchgate_username: Abdul-Jawad-5
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
